### ISSUE TITLE
SECURITY Visible passwords in errorlog

### ISSUE THREAD

**Issue by eieste** [tulir/mautrix-instagram#1]
Hello,

When login to Instagram fails, username and password are in plain text in the error log.
```
[2021-01-03 18:59:02,516] [ERROR@mau.commands] Unhandled error while handling command login <USERNAME> <PASSWORD> from @MXID (ref: 1609694942)
Traceback (most recent call last):
  File "/opt/mautrix-instagram/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 405, in handle
    await self._run_handler(handler, evt)
  File "/opt/mautrix-instagram/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 290, in __call__
    return await self._handler(evt)
  File "/opt/mautrix-instagram/lib/python3.8/site-packages/mautrix_instagram/commands/auth.py", line 68, in login
    resp = await api.login(username, password)
  File "/opt/mautrix-instagram/lib/python3.8/site-packages/mauigpapi/http/login.py", line 53, in login
    return await self.std_http_post("/api/v1/accounts/login/", data=req,
  File "/opt/mautrix-instagram/lib/python3.8/site-packages/mauigpapi/http/base.py", line 121, in std_http_post
    json_data = await self._handle_response(resp)
  File "/opt/mautrix-instagram/lib/python3.8/site-packages/mauigpapi/http/base.py", line 147, in _handle_response
    await self._raise_response_error(resp)
  File "/opt/mautrix-instagram/lib/python3.8/site-packages/mauigpapi/http/base.py", line 162, in _raise_response_error
    raise IGRateLimitError(resp, data)
mauigpapi.errors.response.IGRateLimitError: Request POST /api/v1/accounts/login/ failed: Please wait a few minutes before you try again.
```

https://github.com/tulir/mautrix-instagram/blob/800a4cb97904701143c9de278cdcbfdebe6bc7c2/mauigpapi/http/base.py#L189

This information should not be visible at any time to third parties (not even server admins)
Anyway, thanks for your bridge and the maintenance of it.

Kind Regards

Stefan

**Comment by debdolph** [comment]
Any progress on this?
