### ISSUE TITLE
Matrix -> Instagram messages aren't forwarded

### ISSUE THREAD

**Issue by Govindass** [tulir/mautrix-instagram#11]
when I send a message to instagram user from Matrix, it throws error:

```
Traceback (most recent call last):
  File "/servers/InstagramBridge/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 335, in ensure_joined
    await self.join_room(room_id, max_retries=0)
  File "/servers/InstagramBridge/lib/python3.8/site-packages/mautrix/appservice/api/intent.py", line 83, in wrapper
    return await __method(*args, **kwargs)
  File "/servers/InstagramBridge/lib/python3.8/site-packages/mautrix/client/api/rooms.py", line 252, in join_room
    content = await self.api.request(Method.POST, Path.join[room_id_or_alias],
  File "/servers/InstagramBridge/lib/python3.8/site-packages/mautrix/api.py", line 254, in request
    return await self._send(method, full_url, content, query_params, headers or {})
  File "/servers/InstagramBridge/lib/python3.8/site-packages/mautrix/api.py", line 177, in _send
    raise make_request_error(http_status=response.status,
mautrix.errors.request.MForbidden: You are not invited to this room.
```
if I add instagram-bot to this private conversation manually, then it forwards instagram -> matrix messages, but matrix -> instagram, it says:
```
[2021-04-24 16:46:17,349] [DEBUG@mau.mx] Received Matrix event redacted from @redacted in redacted
[2021-04-24 16:46:17,350] [DEBUG@mau.portal.redacted] Handling Matrix message redacted from redacted
[2021-04-24 16:46:17,551] [DEBUG@mau.portal.redacted] Handled Matrix message redacted -> redacted
[2021-04-24 16:46:17,608] [DEBUG@mau.portal.redacted] Ignoring message redacted by redacted as it was already handled (message.id in dedup queue)
```
if I understood correctly, due to unknown reason it is treating every my message as a duplicate, thus not sending it

**Comment by tulir** [comment]
That looks like it's successfully sending messages to Instagram.

**Comment by Govindass** [comment]
I have checked instagram side, nothing on it

**Comment by Govindass** [comment]
oh it started working now unexpectedly! thank you
