### ISSUE TITLE
Error on first Setup

### ISSUE THREAD

**Issue by DoM1niC** [tulir/mautrix-instagram#2]
I use PostgresSQL and if try to create the Registration.yaml i get this error
**Virtualenv Python 3.9 latest**

```
source bin/activate
pip install --upgrade https://github.com/tulir/mautrix-instagram/tarball/master#egg=mautrix-instagram[all] \
pip install --upgrade psycopg2-binary
python -m mautrix_instagram -g -c config.yaml
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/matrix/bridges/matrix-appservice-instagram/lib/python3.9/site-packages/mautrix_instagram/__main__.py", line 26, in <module>
    from .db import upgrade_table, init as init_db
  File "/opt/matrix/bridges/matrix-appservice-instagram/lib/python3.9/site-packages/mautrix_instagram/db/__init__.py", line 4, in <module>
    from .user import User
  File "/opt/matrix/bridges/matrix-appservice-instagram/lib/python3.9/site-packages/mautrix_instagram/db/user.py", line 21, in <module>
    from mauigpapi.state import AndroidState
  File "/opt/matrix/bridges/matrix-appservice-instagram/lib/python3.9/site-packages/mauigpapi/__init__.py", line 1, in <module>
    from .state import AndroidState
  File "/opt/matrix/bridges/matrix-appservice-instagram/lib/python3.9/site-packages/mauigpapi/state/__init__.py", line 1, in <module>
    from .state import AndroidState
  File "/opt/matrix/bridges/matrix-appservice-instagram/lib/python3.9/site-packages/mauigpapi/state/state.py", line 28, in <module>
    from .device import AndroidDevice
  File "/opt/matrix/bridges/matrix-appservice-instagram/lib/python3.9/site-packages/mauigpapi/state/device.py", line 29, in <module>
    builds = json.loads(pkgutil.get_data("mauigpapi.state", "samples/builds.json"))
  File "/usr/lib/python3.9/pkgutil.py", line 638, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap_external>", line 979, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/matrix/bridges/matrix-appservice-instagram/lib/python3.9/site-packages/mauigpapi/state/samples/builds.json'

```

**Comment by tulir** [comment]
Why are you installing psycopg2? 🤔

**Comment by DoM1niC** [comment]
> Why are you installing psycopg2? 🤔

ok without the Package and clean reinstall it works now THX anyway because psycopg2 depends like facebook/signal Bridge in my case I have to install it manual but here seems not needed...

**Comment by tulir** [comment]
None of my new bridges (twitter, signal, instagram) use psycopg2, only the old ones do (telegram, facebook, hangouts)

**Comment by DoM1niC** [comment]
> None of my new bridges (twitter, signal, instagram) use psycopg2, only the old ones do (telegram, facebook, hangouts)

so I remove it from my Update Stuff now I never notice this important change
