### ISSUE TITLE
Error when login with postgres

### ISSUE THREAD

**Issue by nano-red** [tulir/mautrix-instagram#3]
When trying to login into instagram, the connection is ok but i have this error in log : 

`Exception while syncing
Traceback (most recent call last):
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 117, in _dict_to_attrs
    obj = attrs_type(**new_items)
TypeError: __init__() missing 1 required keyword-only argument: 'inviter'`
`

**Comment by nano-red** [comment]
`Traceback (most recent call last):
  File "/opt/mautrix-instagram/mautrix_instagram/user.py", line 209, in _try_sync
    await self.sync()
  File "/opt/mautrix-instagram/mautrix_instagram/user.py", line 228, in sync
    resp = await self.client.get_inbox()
  File "/opt/mautrix-instagram/mauigpapi/http/thread.py", line 39, in get_inbox
    response_type=DMInboxResponse)
  File "/opt/mautrix-instagram/mauigpapi/http/base.py", line 138, in std_http_get
    return response_type.deserialize(json_data)
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 285, in deserialize
    return _dict_to_attrs(cls, data)
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 113, in _dict_to_attrs
    field.metadata.get("ignore_errors", False))
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 136, in _try_deserialize
    return _deserialize(cls, value, default)
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 173, in _deserialize
    return _dict_to_attrs(cls, value, default, default_if_empty=True)
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 113, in _dict_to_attrs
    field.metadata.get("ignore_errors", False))
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 136, in _try_deserialize
    return _deserialize(cls, value, default)
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 187, in _deserialize
    return [_deserialize(item_cls, item) for item in value]
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 187, in <listcomp>
    return [_deserialize(item_cls, item) for item in value]
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 173, in _deserialize
    return _dict_to_attrs(cls, value, default, default_if_empty=True)
  File "/opt/mautrix-instagram/lib/python3.7/site-packages/mautrix/types/util/serializable_attrs.py", line 126, in _dict_to_attrs
    f"Missing value for required key {field.name} in {attrs_type.__name__}") from e
mautrix.types.util.serializable.SerializerError: Missing value for required key inviter in Thread
`

**Comment by Anas-Sherif** [comment]
were you able to fix it?
