### ISSUE TITLE
FileNotFoundError: /opt/mautrix-instagram/lib/python3.9/site-packages/mauigpapi/state/samples/builds.json

### ISSUE THREAD

**Issue by myOmikron** [tulir/mautrix-instagram#4]
When installing the bridge following error occurs: 

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/mautrix-instagram/lib/python3.9/site-packages/mautrix_instagram/__main__.py", line 22, in <module>
    from .db import upgrade_table, init as init_db
  File "/opt/mautrix-instagram/lib/python3.9/site-packages/mautrix_instagram/db/__init__.py", line 4, in <module>
    from .user import User
  File "/opt/mautrix-instagram/lib/python3.9/site-packages/mautrix_instagram/db/user.py", line 21, in <module>
    from mauigpapi.state import AndroidState
  File "/opt/mautrix-instagram/lib/python3.9/site-packages/mauigpapi/__init__.py", line 1, in <module>
    from .state import AndroidState
  File "/opt/mautrix-instagram/lib/python3.9/site-packages/mauigpapi/state/__init__.py", line 1, in <module>
    from .state import AndroidState
  File "/opt/mautrix-instagram/lib/python3.9/site-packages/mauigpapi/state/state.py", line 28, in <module>
    from .device import AndroidDevice
  File "/opt/mautrix-instagram/lib/python3.9/site-packages/mauigpapi/state/device.py", line 29, in <module>
    builds = json.loads(pkgutil.get_data("mauigpapi.state", "samples/builds.json"))
  File "/usr/lib/python3.9/pkgutil.py", line 638, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap_external>", line 979, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/mautrix-instagram/lib/python3.9/site-packages/mauigpapi/state/samples/builds.json'
```

I've installed in a new venv on a new user.
`pip freeze`
```
aiohttp==3.7.4.post0
async-timeout==3.0.1
asyncpg==0.21.0
attrs==20.3.0
cffi==1.14.5
chardet==4.0.0
commonmark==0.9.1
future==0.18.2
idna==3.1
mautrix==0.8.16
mautrix-instagram==0.1.0b1
multidict==5.1.0
paho-mqtt==1.5.1
Pillow==8.1.2
prometheus-client==0.9.0
pycparser==2.20
pycryptodome==3.10.1
python-magic==0.4.22
python-olm==3.1.3
ruamel.yaml==0.16.13
ruamel.yaml.clib==0.2.2
typing-extensions==3.7.4.3
unpaddedbase64==1.1.0
yarl==1.6.3
```

The packages were installed (while venv was activated) with the following command:

`pip install -U pip mautrix-instagram[all]`

**Comment by tulir** [comment]
Use the master branch for now
