### ISSUE TITLE
Missing value for required key last_seen_at

### ISSUE THREAD

**Issue by languitar** [tulir/mautrix-instagram#5]
I gave this bridge a try. However, when someone sends a private message, nothing happens with the current latest version. Instead, the log shows the following exception:

```
instagram_1  | [2021-03-16 20:06:09,379] [ERROR@mau.instagram.mqtt.@languitar:matrix.semipol.de] Error in incoming MQTT message handler
instagram_1  | Traceback (most recent call last):
instagram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 131, in _dict_to_attrs
instagram_1  |     obj = attrs_type(**new_items)
instagram_1  | TypeError: __init__() missing 1 required keyword-only argument: 'last_seen_at'
instagram_1  | 
instagram_1  | The above exception was the direct cause of the following exception:
instagram_1  | 
instagram_1  | Traceback (most recent call last):
instagram_1  |   File "/opt/mautrix-instagram/mauigpapi/mqtt/conn.py", line 349, in _on_message_handler
instagram_1  |     self._on_message_sync(message.payload)
instagram_1  |   File "/opt/mautrix-instagram/mauigpapi/mqtt/conn.py", line 292, in _on_message_sync
instagram_1  |     self._on_messager_sync_item(part, parsed_item)
instagram_1  |   File "/opt/mautrix-instagram/mauigpapi/mqtt/conn.py", line 276, in _on_messager_sync_item
instagram_1  |     evt = ThreadSyncEvent.deserialize(raw_message)
instagram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 297, in deserialize
instagram_1  |     return _dict_to_attrs(cls, data)
instagram_1  |   File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 137, in _dict_to_attrs
instagram_1  |     raise SerializerError("Missing value for required key "
instagram_1  | mautrix.types.util.serializable.SerializerError: Missing value for required key last_seen_at in ThreadSyncEvent
```

"Image": "sha256:6127f7fb2bb797ba8f702ac219809593ecda688012229c58da37cc3e774a81ae"

**Comment by languitar** [comment]
Woa, that was quick! Thanks a lot!
